version: '3.8'

services:
  forex-bot:
    build: .
    volumes:
      - ./logs:/app/logs
      - .env:/app/.env
    ports:
      - "8000:8000"
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
